{% set name = "chronon-ai" %}
{% set version = "0.0.103" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4f1ce1dad3a86e1de4f21ee80a2906abee837ab2939540e0fa3a212cbb15b27b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - CHRONON_VERSION_STR={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click
    - thrift

# Wait for upstream to fix thrift pin before adding pip check
test:
  imports:
    - ai.chronon
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Chronon python API library
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/airbnb/chronon

extra:
  recipe-maintainers:
    - iamthebot
    - nikhilsimha
    - pengyu-hou
    - hzding621
    - snapbug
