{% set name = "chronon-ai" %}
{% set version = "0.0.90" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6e256a55523c3e9090e11ffd3ca3f015988d5adb94a0b1e45e44ffabbc76f4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - CHRONON_VERSION_STR={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click
    - thrift

# Wait for upstream to fix thrift pin before adding pip check
test:
  imports:
    - ai.chronon
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Chronon python API library
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/airbnb/chronon

extra:
  recipe-maintainers:
    - iamthebot
    - nikhilsimha
    - pengyu-hou
    - hzding621
    - snapbug
