{% set name = "chronon-ai" %}
{% set version = "0.0.75" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chronon-ai-{{ version }}.tar.gz
  sha256: 361bbdeaee563ac150bd87945c2af54a1b6b77b0eb1b54e2bea828acf2b6fe87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - CHRONON_VERSION_STR={{ version }}

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - click
    - thrift <0.14

test:
  imports:
    - ai.chronon
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Chronon python API library
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/airbnb/chronon

extra:
  recipe-maintainers:
    - iamthebot
    - nikhilsimha
