{% set name = "chronon-ai" %}
{% set version = "0.0.78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b76a77cd1aa60ec8cd9965eb7b80c52b91b182a52c9e82c55706387a2a55f01e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - CHRONON_VERSION_STR={{ version }}

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - click
    - thrift <0.14

test:
  imports:
    - ai.chronon
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Chronon python API library
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/airbnb/chronon

extra:
  recipe-maintainers:
    - iamthebot
    - nikhilsimha
    - pengyu-hou
    - hzding621
