{% set name = "chronon-ai" %}
{% set version = "0.0.115" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d617b2a4e0e8ecfc65fdb1ffbd101097a039a3f749f18be8abcf4516bdea4f14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - CHRONON_VERSION_STR={{ version }}

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click
    - thrift

# Wait for upstream to fix thrift pin before adding pip check
test:
  imports:
    - ai.chronon
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Chronon python API library
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/airbnb/chronon

extra:
  recipe-maintainers:
    - iamthebot
    - nikhilsimha
    - pengyu-hou
    - hzding621
    - snapbug
