{% set name = "chronon-ai" %}
{% set version = "0.0.86" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eae9cc3052564608503d4edf7cda4935ffd416542df6116b93ad9e3f787626a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  script_env:
    - CHRONON_VERSION_STR={{ version }}

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - click
    - thrift

# Wait for upstream to fix thrift pin before adding pip check
test:
  imports:
    - ai.chronon
  requires:
    - pip

about:
  summary: Chronon python API library
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/airbnb/chronon

extra:
  recipe-maintainers:
    - iamthebot
    - nikhilsimha
    - pengyu-hou
    - hzding621
    - snapbug
